// <auto-generated />
using System;
using IfiNavet.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IfiNavet.Persistence.Migrations
{
    [DbContext(typeof(IfiNavetDbContext))]
    [Migration("20190307082613_Key")]
    partial class Key
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IfiNavet.Core.Entities.Events.IfiEvent", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Food");

                    b.Property<string>("Location");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<bool>("Open");

                    b.Property<int>("PlacesLeft");

                    b.HasKey("Link");

                    b.ToTable("IfiEvents");
                });

            modelBuilder.Entity("IfiNavet.Core.Entities.Users.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = "c4c833a3-fa25-419b-8b0e-c7c952d70fc3",
                            Password = "ifibot123",
                            Username = "sodnrefi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
