// <auto-generated />
using System;
using IfiNavet.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IfiNavet.Persistence.Migrations
{
    [DbContext(typeof(IfiNavetDbContext))]
    partial class IfiNavetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IfiNavet.Core.Entities.IfiEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Food");

                    b.Property<string>("Link");

                    b.Property<string>("Location");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<bool>("Open");

                    b.Property<int>("PlacesLeft");

                    b.HasKey("Id");

                    b.ToTable("IfiEvents");
                });

            modelBuilder.Entity("IfiNavet.Core.Entities.Users.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = "8ca276ca-cd53-4233-9805-dadbf08535ac",
                            Password = "ifibot123",
                            Username = "sodnrefi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
